version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/toeflbackend
    owner: ec2-user
    group: ec2-user
permissions:
  - object: /var/www/toeflbackend
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/npmstart.sh
      timeout: 300
      runas: ec2-user
